import = [
	"~/.config/alacritty/themes/alacritty-theme/themes/gruvbox_dark.toml"
]

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style="Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style="Italic"
